// Gallery photos.
//
// Any image in src/assets/gallery/ (JPEG, PNG or WebP, ideally ~2000px on
// the long side and under ~400 KB) is shown automatically, sorted by file
// name: prefix names with 01-, 02-… to choose the order. Descriptive,
// hyphenated names help image search ("03-chateau-de-voltaire-charmilles.jpg").
//
// Give each photo a title and a legend in every language below. The title
// is the alt text, and both appear under the photo and in the full-screen
// view. Photos without an entry get a title made from the file name
// ("03-les-charmilles.jpg" → "Les charmilles") until one is written.
//
// While there are fewer than six photos, placeholder frames fill the grid.

import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export const details = {
  "02-chateau-de-voltaire-chambre-toilette.webp": {
    title: {
      fr: "La table de toilette d’une chambre du château",
      en: "The dressing table of a bedroom in the château",
      de: "Der Toilettentisch eines Schlafzimmers im Schloss",
      ru: "Туалетный столик в спальне замка",
      es: "El tocador de un dormitorio del castillo",
      it: "La toeletta di una camera da letto del castello",
      pt: "O toucador de um quarto do castelo",
      nl: "De kaptafel van een slaapkamer in het kasteel",
      pl: "Toaletka w jednej z sypialni zamku",
      uk: "Туалетний столик у спальні замку",
      zh: "城堡卧室中的梳妆台",
      ja: "城館の寝室にある化粧台",
      ko: "성 안 침실의 화장대",
      ar: "طاولة الزينة في إحدى غرف النوم بالقصر",
      hi: "शातो के एक शयनकक्ष की श्रृंगार-मेज़",
      tr: "Şatodaki bir yatak odasının tuvalet masası",
    },
    legend: {
      fr: "Soieries jaunes à motifs pourpres, cheminée de marbre surmontée d’un trumeau, fauteuils assortis et tapis fleuri : la toilette, avec son miroir et ses pots de porcelaine, évoque les rituels du matin au XVIIIe siècle.",
      en: "Yellow silks patterned in crimson, a marble fireplace beneath a tall mirror, matching armchairs and a floral carpet: the dressing table, with its mirror and porcelain pots, recalls the morning rituals of the 18th century.",
      de: "Gelbe Seide mit purpurroten Mustern, ein Marmorkamin unter einem hohen Spiegel, passende Sessel und ein geblümter Teppich: Der Toilettentisch mit Spiegel und Porzellandosen erinnert an die Morgenrituale des 18. Jahrhunderts.",
      ru: "Жёлтые шелка с пурпурным узором, мраморный камин под высоким зеркалом, кресла в тон и цветочный ковёр: туалетный столик с зеркалом и фарфоровыми баночками напоминает об утренних ритуалах XVIII века.",
      es: "Sedas amarillas con motivos carmesí, una chimenea de mármol bajo un alto espejo, sillones a juego y una alfombra floreada: el tocador, con su espejo y sus tarros de porcelana, evoca los rituales matinales del siglo XVIII.",
      it: "Sete gialle a motivi cremisi, un camino di marmo sotto un’alta specchiera, poltrone coordinate e un tappeto fiorito: la toeletta, con il suo specchio e i vasetti di porcellana, evoca i rituali mattutini del Settecento.",
      pt: "Sedas amarelas com padrões carmesim, uma lareira de mármore sob um alto espelho, poltronas a condizer e um tapete florido: o toucador, com o seu espelho e os seus potes de porcelana, evoca os rituais matinais do século XVIII.",
      nl: "Gele zijde met karmozijnrode motieven, een marmeren schouw onder een hoge spiegel, bijpassende fauteuils en een gebloemd tapijt: de kaptafel, met haar spiegel en porseleinen potjes, roept de ochtendrituelen van de 18e eeuw op.",
      pl: "Żółte jedwabie w karmazynowe wzory, marmurowy kominek pod wysokim lustrem, dobrane do kompletu fotele i kwiecisty dywan: toaletka z lustrem i porcelanowymi pojemnikami przywołuje poranne rytuały XVIII wieku.",
      uk: "Жовті шовки з багряним візерунком, мармуровий камін під високим дзеркалом, крісла в тон і квітчастий килим: туалетний столик із дзеркалом і порцеляновими баночками нагадує про ранкові ритуали XVIII століття.",
      zh: "饰有深红图案的黄色丝绸、高大镜子下的大理石壁炉、配套的扶手椅和花卉地毯：带镜子和瓷罐的梳妆台，令人想起十八世纪的晨间梳妆仪式。",
      ja: "深紅の模様が入った黄色の絹、背の高い鏡の下の大理石の暖炉、揃いの肘掛け椅子、花柄の絨毯。鏡と磁器の壺を備えた化粧台は、18世紀の朝の身支度の習わしを思い起こさせます。",
      ko: "진홍색 무늬가 들어간 노란 비단, 높은 거울 아래의 대리석 벽난로, 같은 짝의 안락의자와 꽃무늬 카펫. 거울과 도자기 단지가 놓인 화장대는 18세기 아침의 몸단장 의식을 떠올리게 합니다.",
      ar: "حرائر صفراء بزخارف قرمزية، ومدفأة رخامية تحت مرآة عالية، ومقاعد بذراعين متناسقة وسجادة مزهّرة: طاولة الزينة، بمرآتها وأوانيها الخزفية، تستحضر طقوس الصباح في القرن الثامن عشر.",
      hi: "गहरे लाल बेल-बूटों वाले पीले रेशम, ऊँचे दर्पण के नीचे संगमरमर की अँगीठी, मेल खाती आरामकुर्सियाँ और फूलदार क़ालीन: दर्पण और चीनी मिट्टी के पात्रों वाली श्रृंगार-मेज़ 18वीं सदी की सुबह की रस्मों की याद दिलाती है।",
      tr: "Kızıl desenli sarı ipekler, yüksek bir aynanın altında mermer bir şömine, takım koltuklar ve çiçekli bir halı: aynası ve porselen kaplarıyla tuvalet masası, 18. yüzyılın sabah ritüellerini anımsatıyor.",
    },
  },
  "01-chateau-de-voltaire-salon.jpg": {
    title: {
      fr: "Le salon du Château de Voltaire",
      en: "The salon of the Château de Voltaire",
      de: "Der Salon im Schloss Voltaire",
      ru: "Салон в замке Вольтера",
      es: "El salón del Château de Voltaire",
      it: "Il salone del Château de Voltaire",
      pt: "O salão do Château de Voltaire",
      nl: "De salon van het Château de Voltaire",
      pl: "Salon w Château de Voltaire",
      uk: "Салон у замку Вольтера",
      zh: "伏尔泰城堡的沙龙",
      ja: "ヴォルテール城のサロン",
      ko: "볼테르 성의 살롱",
      ar: "صالون قصر فولتير",
      hi: "शातो द वोल्टेयर का सैलून",
      tr: "Château de Voltaire’in salonu",
    },
    legend: {
      fr: "Tentures rayées rouge et vert, portrait de Voltaire jeune dans son cadre ovale, cheminée de marbre et tables de jeu dressées : c’est dans ce décor que l’on recevait les visiteurs du château.",
      en: "Red-and-green striped hangings, a portrait of the young Voltaire in its oval frame, a marble fireplace and game tables laid out: the setting in which the château’s visitors were received.",
      de: "Rot-grün gestreifte Wandbespannungen, ein Porträt des jungen Voltaire im ovalen Rahmen, ein Marmorkamin und gedeckte Spieltische: In diesem Rahmen empfing man die Gäste des Schlosses.",
      ru: "Красно-зелёные полосатые обивки стен, портрет молодого Вольтера в овальной раме, мраморный камин и накрытые игровые столики — в этой обстановке принимали гостей замка.",
      es: "Colgaduras a rayas rojas y verdes, un retrato del joven Voltaire en su marco ovalado, una chimenea de mármol y mesas de juego dispuestas: el escenario en el que se recibía a los visitantes del castillo.",
      it: "Tappezzerie a righe rosse e verdi, un ritratto del giovane Voltaire nella sua cornice ovale, un camino di marmo e tavoli da gioco apparecchiati: l’ambiente in cui si ricevevano gli ospiti del castello.",
      pt: "Tapeçarias às riscas vermelhas e verdes, um retrato do jovem Voltaire na sua moldura oval, uma lareira de mármore e mesas de jogo preparadas: o cenário em que se recebiam os visitantes do castelo.",
      nl: "Rood-groen gestreepte wandbespanning, een portret van de jonge Voltaire in een ovale lijst, een marmeren schouw en klaargezette speeltafels: het decor waarin de bezoekers van het kasteel werden ontvangen.",
      pl: "Obicia w czerwono-zielone pasy, portret młodego Woltera w owalnej ramie, marmurowy kominek i nakryte stoliki do gry: w tym wnętrzu przyjmowano gości zamku.",
      uk: "Червоно-зелені смугасті оббивки стін, портрет молодого Вольтера в овальній рамі, мармуровий камін і накриті ігрові столики: у цій обстановці приймали гостей замку.",
      zh: "红绿条纹的墙幔、椭圆画框中的青年伏尔泰肖像、大理石壁炉和摆好的牌桌：城堡的访客便是在这样的环境中受到接待。",
      ja: "赤と緑の縞模様の壁布、楕円の額に収められた若き日のヴォルテールの肖像、大理石の暖炉、そして支度の整ったゲームテーブル。城館を訪れた客人たちは、この空間で迎えられました。",
      ko: "붉은색과 초록색 줄무늬 벽걸이 천, 타원형 액자 속 젊은 볼테르의 초상화, 대리석 벽난로와 차려진 게임 테이블: 성을 찾은 방문객들을 맞이하던 공간입니다.",
      ar: "ستائر جدارية مخططة بالأحمر والأخضر، وصورة لفولتير شاباً في إطارها البيضاوي، ومدفأة رخامية وطاولات لعب مُعدّة: هذا هو المكان الذي كان يُستقبل فيه زوار القصر.",
      hi: "लाल-हरी धारियों वाले पर्दे, अंडाकार फ़्रेम में युवा वोल्टेयर का चित्र, संगमरमर की अँगीठी और सजी हुई खेल-मेज़ें: यही वह परिवेश है जिसमें शातो के आगंतुकों का स्वागत किया जाता था।",
      tr: "Kırmızı-yeşil çizgili duvar kumaşları, oval çerçevesi içinde genç Voltaire’in portresi, mermer bir şömine ve hazırlanmış oyun masaları: şatonun ziyaretçilerinin ağırlandığı mekân.",
    },
  },
  "03-chateau-de-voltaire-salon-tables-de-jeu.jpg": {
    title: {
      fr: "Les tables de jeu du salon et le portrait de Frédéric II",
      en: "The salon’s game tables and the portrait of Frederick II",
      de: "Die Spieltische des Salons und das Bildnis Friedrichs II.",
      ru: "Игровые столики салона и портрет Фридриха II",
      es: "Las mesas de juego del salón y el retrato de Federico II",
      it: "I tavoli da gioco del salone e il ritratto di Federico II",
      pt: "As mesas de jogo do salão e o retrato de Frederico II",
      nl: "De speeltafels van de salon en het portret van Frederik II",
      pl: "Stoliki do gry w salonie i portret Fryderyka II",
      uk: "Ігрові столики салону та портрет Фрідріха II",
      zh: "沙龙里的牌桌与腓特烈二世肖像",
      ja: "サロンのゲームテーブルとフリードリヒ2世の肖像",
      ko: "살롱의 게임 테이블과 프리드리히 2세의 초상화",
      ar: "طاولات اللعب في الصالون وصورة فريدريك الثاني",
      hi: "सैलून की खेल-मेज़ें और फ्रेडरिक द्वितीय का चित्र",
      tr: "Salonun oyun masaları ve II. Friedrich’in portresi",
    },
    legend: {
      fr: "Cartes, éventail et tasses sur la table de jeu, damier marqueté, canapé de velours cramoisi et pendule de bronze doré sur la cheminée de marbre. Au mur, Frédéric II de Prusse, ami et correspondant de Voltaire.",
      en: "Cards, a fan and cups on the game table, an inlaid chessboard, a crimson velvet sofa and a gilt-bronze clock on the marble fireplace. On the wall, Frederick II of Prussia, Voltaire’s friend and correspondent.",
      de: "Karten, Fächer und Tassen auf dem Spieltisch, ein eingelegtes Schachbrett, ein karmesinrotes Samtsofa und eine vergoldete Bronzeuhr auf dem Marmorkamin. An der Wand Friedrich II. von Preußen, Voltaires Freund und Briefpartner.",
      ru: "Карты, веер и чашки на игровом столе, инкрустированная шахматная доска, малиновый бархатный диван и часы из золочёной бронзы на мраморном камине. На стене — Фридрих II Прусский, друг и корреспондент Вольтера.",
      es: "Naipes, un abanico y tazas sobre la mesa de juego, un tablero de ajedrez de marquetería, un sofá de terciopelo carmesí y un reloj de bronce dorado sobre la chimenea de mármol. En la pared, Federico II de Prusia, amigo y corresponsal de Voltaire.",
      it: "Carte, un ventaglio e tazze sul tavolo da gioco, una scacchiera intarsiata, un divano di velluto cremisi e una pendola di bronzo dorato sul camino di marmo. Alla parete, Federico II di Prussia, amico e corrispondente di Voltaire.",
      pt: "Cartas, um leque e chávenas na mesa de jogo, um tabuleiro de xadrez marchetado, um sofá de veludo carmesim e um relógio de bronze dourado sobre a lareira de mármore. Na parede, Frederico II da Prússia, amigo e correspondente de Voltaire.",
      nl: "Kaarten, een waaier en kopjes op de speeltafel, een ingelegd schaakbord, een karmozijnrode fluwelen sofa en een klok van verguld brons op de marmeren schouw. Aan de muur Frederik II van Pruisen, vriend en correspondent van Voltaire.",
      pl: "Karty, wachlarz i filiżanki na stoliku do gry, intarsjowana szachownica, karmazynowa aksamitna sofa i zegar ze złoconego brązu na marmurowym kominku. Na ścianie Fryderyk II Pruski, przyjaciel i korespondent Woltera.",
      uk: "Карти, віяло й чашки на ігровому столі, інкрустована шахівниця, малинова оксамитова канапа та годинник із позолоченої бронзи на мармуровому каміні. На стіні — Фрідріх II Прусський, друг і кореспондент Вольтера.",
      zh: "牌桌上放着纸牌、折扇和杯子，还有镶嵌棋盘、深红天鹅绒沙发，以及大理石壁炉上的鎏金铜钟。墙上是普鲁士的腓特烈二世，伏尔泰的朋友和通信者。",
      ja: "ゲームテーブルの上のトランプ、扇、カップ、象嵌のチェス盤、深紅のビロードのソファ、そして大理石の暖炉の上の金メッキのブロンズ時計。壁には、ヴォルテールの友人であり文通相手でもあったプロイセンのフリードリヒ2世。",
      ko: "게임 테이블 위의 카드와 부채와 찻잔, 상감 체스판, 진홍색 벨벳 소파, 대리석 벽난로 위의 금박 청동 시계. 벽에는 볼테르의 친구이자 서신 교환 상대였던 프로이센의 프리드리히 2세가 걸려 있습니다.",
      ar: "أوراق لعب ومروحة يدوية وفناجين على طاولة اللعب، ورقعة شطرنج مطعّمة، وأريكة من المخمل القرمزي، وساعة من البرونز المذهّب فوق المدفأة الرخامية. وعلى الجدار فريدريك الثاني ملك بروسيا، صديق فولتير ومراسله.",
      hi: "खेल-मेज़ पर ताश, पंखा और प्याले, जड़ाऊ शतरंज-पट, गहरे लाल मखमल का सोफ़ा और संगमरमर की अँगीठी पर सोने का पानी चढ़ी काँसे की घड़ी। दीवार पर प्रशा के फ्रेडरिक द्वितीय, वोल्टेयर के मित्र और पत्र-मित्र।",
      tr: "Oyun masasında iskambil kâğıtları, bir yelpaze ve fincanlar, kakma bir satranç tahtası, kızıl kadife bir kanepe ve mermer şöminenin üzerinde yaldızlı bronz bir saat. Duvarda, Voltaire’in dostu ve mektup arkadaşı Prusya Kralı II. Friedrich.",
    },
  },
  "04-chateau-de-voltaire-eglise-deo-erexit-voltaire.jpg": {
    title: {
      fr: "L’église « Deo erexit Voltaire » dans le parc",
      en: "The “Deo erexit Voltaire” church in the park",
      de: "Die Kirche „Deo erexit Voltaire“ im Park",
      ru: "Церковь «Deo erexit Voltaire» в парке",
      es: "La iglesia «Deo erexit Voltaire» en el parque",
      it: "La chiesa «Deo erexit Voltaire» nel parco",
      pt: "A igreja «Deo erexit Voltaire» no parque",
      nl: "De kerk “Deo erexit Voltaire” in het park",
      pl: "Kościół „Deo erexit Voltaire” w parku",
      uk: "Церква «Deo erexit Voltaire» у парку",
      zh: "园中的“Deo erexit Voltaire”教堂",
      ja: "庭園に建つ「Deo erexit Voltaire」の教会",
      ko: "공원 안의 “Deo erexit Voltaire” 교회",
      ar: "كنيسة «Deo erexit Voltaire» في الحديقة",
      hi: "पार्क में “Deo erexit Voltaire” गिरजाघर",
      tr: "Parktaki “Deo erexit Voltaire” kilisesi",
    },
    legend: {
      fr: "Au bout des allées de gravier et des haies taillées, la petite église que Voltaire fit rebâtir en 1761 : son fronton porte la célèbre dédicace « Deo erexit Voltaire », « Voltaire l’a élevée à Dieu ».",
      en: "Beyond the gravel paths and clipped hedges stands the little church Voltaire had rebuilt in 1761. Its pediment bears the famous dedication “Deo erexit Voltaire”, “Voltaire raised it to God”.",
      de: "Hinter Kieswegen und geschnittenen Hecken steht die kleine Kirche, die Voltaire 1761 neu errichten ließ. Ihr Giebel trägt die berühmte Widmung „Deo erexit Voltaire“ – „Voltaire hat sie Gott errichtet“.",
      ru: "За гравийными дорожками и стрижеными живыми изгородями — небольшая церковь, перестроенная Вольтером в 1761 году. На её фронтоне знаменитое посвящение «Deo erexit Voltaire» — «Богу воздвиг Вольтер».",
      es: "Más allá de los caminos de grava y los setos recortados se alza la pequeña iglesia que Voltaire mandó reconstruir en 1761. Su frontón lleva la célebre dedicatoria «Deo erexit Voltaire», «Voltaire la erigió a Dios».",
      it: "Oltre i viali di ghiaia e le siepi potate sorge la piccola chiesa che Voltaire fece ricostruire nel 1761. Il suo frontone reca la celebre dedica «Deo erexit Voltaire», «Voltaire la eresse a Dio».",
      pt: "Para lá dos caminhos de gravilha e das sebes aparadas ergue-se a pequena igreja que Voltaire mandou reconstruir em 1761. O seu frontão ostenta a célebre dedicatória «Deo erexit Voltaire», «Voltaire ergueu-a a Deus».",
      nl: "Voorbij de grindpaden en geschoren hagen staat het kerkje dat Voltaire in 1761 liet herbouwen. Het fronton draagt de beroemde opdracht “Deo erexit Voltaire”, “Voltaire heeft haar voor God opgericht”.",
      pl: "Za żwirowymi alejkami i przyciętymi żywopłotami stoi niewielki kościół, który Wolter kazał odbudować w 1761 roku. Na jego frontonie widnieje słynna dedykacja „Deo erexit Voltaire”, „Wolter wzniósł go Bogu”.",
      uk: "За гравійними доріжками й підстриженими живоплотами стоїть невелика церква, яку Вольтер звелів перебудувати 1761 року. На її фронтоні — знаменита присвята «Deo erexit Voltaire», «Богові звів Вольтер».",
      zh: "穿过碎石小径和修剪整齐的树篱，便是伏尔泰于1761年下令重建的小教堂。其山墙上刻着著名的献词“Deo erexit Voltaire”，即“伏尔泰为上帝而建”。",
      ja: "砂利道と刈り込まれた生け垣の先に、ヴォルテールが1761年に再建させた小さな教会が建っています。そのペディメントには有名な献辞「Deo erexit Voltaire」、「ヴォルテール、神のためにこれを建つ」が刻まれています。",
      ko: "자갈길과 다듬어진 산울타리 너머에 볼테르가 1761년에 재건하게 한 작은 교회가 서 있습니다. 그 박공에는 유명한 헌사 “Deo erexit Voltaire”, 곧 “볼테르가 하느님께 세웠노라”가 새겨져 있습니다.",
      ar: "خلف الممرات المفروشة بالحصى والأسيجة المشذّبة تقوم الكنيسة الصغيرة التي أعاد فولتير بناءها عام 1761. ويحمل جملونها الإهداء الشهير «Deo erexit Voltaire»، أي «فولتير شيّدها لله».",
      hi: "बजरी के रास्तों और कटी-छँटी झाड़ियों के पार वह छोटा गिरजाघर है जिसे वोल्टेयर ने 1761 में फिर से बनवाया था। उसके त्रिकोणीय शिखर पर प्रसिद्ध समर्पण-लेख “Deo erexit Voltaire” अंकित है, “वोल्टेयर ने इसे ईश्वर के लिए खड़ा किया”।",
      tr: "Çakıllı yolların ve budanmış çitlerin ötesinde, Voltaire’in 1761’de yeniden inşa ettirdiği küçük kilise yükselir. Alınlığında ünlü ithaf yazısı “Deo erexit Voltaire”, “Voltaire onu Tanrı için yükseltti” yer alır.",
    },
  },
  "05-chateau-de-voltaire-jardin-fontaine.jpg": {
    title: {
      fr: "Sylvie descend vers le jardin et sa fontaine",
      en: "Sylvie walks down to the garden and its fountain",
      de: "Sylvie auf dem Weg zum Garten und seinem Brunnen",
      ru: "Сильви спускается в сад к фонтану",
      es: "Sylvie baja hacia el jardín y su fuente",
      it: "Sylvie scende verso il giardino e la sua fontana",
      pt: "Sylvie desce até ao jardim e à sua fonte",
      nl: "Sylvie loopt naar beneden, naar de tuin en de fontein",
      pl: "Sylvie schodzi do ogrodu i jego fontanny",
      uk: "Сільві спускається до саду з фонтаном",
      zh: "西尔维走向花园和喷泉",
      ja: "庭園と噴水へと下りていくシルヴィ",
      ko: "정원과 분수로 내려가는 실비",
      ar: "سيلفي تنزل نحو الحديقة ونافورتها",
      hi: "सिल्वी बग़ीचे और उसके फ़व्वारे की ओर उतरती हुई",
      tr: "Sylvie bahçeye ve çeşmesine doğru iniyor",
    },
    legend: {
      fr: "Bassin aux nénuphars et sa statue de bronze, ifs taillés en cône, allées de gravier et, sous la galerie vitrée, une terrasse ombragée : l’endroit idéal pour une pause après la visite.",
      en: "A water-lily basin with its bronze statue, cone-shaped yews, gravel paths and, beneath the glazed gallery, a shaded terrace: the ideal spot for a break after the tour.",
      de: "Ein Seerosenbecken mit Bronzestatue, kegelförmig geschnittene Eiben, Kieswege und unter der verglasten Galerie eine schattige Terrasse: der ideale Ort für eine Pause nach der Führung.",
      ru: "Бассейн с кувшинками и бронзовой статуей, подстриженные конусом тисы, гравийные дорожки, а под застеклённой галереей — тенистая терраса: идеальное место для отдыха после экскурсии.",
      es: "Un estanque de nenúfares con su estatua de bronce, tejos podados en cono, caminos de grava y, bajo la galería acristalada, una terraza a la sombra: el lugar ideal para una pausa después de la visita.",
      it: "Una vasca di ninfee con la sua statua di bronzo, tassi potati a cono, viali di ghiaia e, sotto la galleria vetrata, una terrazza ombreggiata: il luogo ideale per una pausa dopo la visita.",
      pt: "Um tanque de nenúfares com a sua estátua de bronze, teixos podados em cone, caminhos de gravilha e, sob a galeria envidraçada, um terraço à sombra: o local ideal para uma pausa depois da visita.",
      nl: "Een waterleliebassin met een bronzen beeld, kegelvormig gesnoeide taxussen, grindpaden en, onder de glazen galerij, een schaduwrijk terras: de ideale plek voor een pauze na de rondleiding.",
      pl: "Basen z liliami wodnymi i brązowym posągiem, cisy przycięte w stożki, żwirowe alejki, a pod przeszkloną galerią zacieniony taras: idealne miejsce na odpoczynek po zwiedzaniu.",
      uk: "Басейн із лататтям і бронзовою статуєю, тиси, підстрижені конусом, гравійні доріжки, а під заскленою галереєю — затінена тераса: ідеальне місце для відпочинку після екскурсії.",
      zh: "立有青铜雕像的睡莲池、修剪成圆锥形的紫杉、碎石小径，以及玻璃长廊下的荫凉露台：参观之后小憩的理想之处。",
      ja: "ブロンズ像の立つ睡蓮の池、円錐形に刈り込まれたイチイ、砂利道、そしてガラス張りのギャラリーの下の日陰のテラス。見学のあとにひと休みするのに最適な場所です。",
      ko: "청동 조각상이 있는 수련 연못, 원뿔 모양으로 다듬은 주목, 자갈길, 그리고 유리 회랑 아래의 그늘진 테라스. 투어를 마친 뒤 쉬어 가기에 더없이 좋은 곳입니다.",
      ar: "حوض زنابق ماء يتوسطه تمثال برونزي، وأشجار طقسوس مشذّبة على شكل مخروط، وممرات من الحصى، وتحت الرواق الزجاجي شرفة ظليلة: المكان المثالي لاستراحة بعد الجولة.",
      hi: "काँसे की मूर्ति वाला कुमुदिनी-ताल, शंकु के आकार में कटे यू के पेड़, बजरी के रास्ते और काँच से घिरी दीर्घा के नीचे छायादार छत: भ्रमण के बाद विश्राम के लिए आदर्श जगह।",
      tr: "Bronz heykelli nilüfer havuzu, koni biçiminde budanmış porsuk ağaçları, çakıllı yollar ve camlı galerinin altında gölgeli bir teras: turdan sonra mola vermek için ideal bir yer.",
    },
  },
  "06-chambre-de-voltaire-ferney.jpg": {
    title: {
      fr: "La chambre de Voltaire",
      en: "Voltaire’s bedroom",
      de: "Voltaires Schlafzimmer",
      ru: "Спальня Вольтера",
      es: "El dormitorio de Voltaire",
      it: "La camera da letto di Voltaire",
      pt: "O quarto de Voltaire",
      nl: "De slaapkamer van Voltaire",
      pl: "Sypialnia Woltera",
      uk: "Спальня Вольтера",
      zh: "伏尔泰的卧室",
      ja: "ヴォルテールの寝室",
      ko: "볼테르의 침실",
      ar: "غرفة نوم فولتير",
      hi: "वोल्टेयर का शयनकक्ष",
      tr: "Voltaire’in yatak odası",
    },
    legend: {
      fr: "Boiseries bleues, soieries dorées et plafond orné de rinceaux : un lit à baldaquin et un grand portrait impérial dont l’inscription précise qu’il fut « donné à M. de Voltaire le 15 juillet 1770 ».",
      en: "Blue panelling, golden silks and a ceiling of scrolling ornament: a canopy bed and a large imperial portrait whose inscription records that it was “given to M. de Voltaire on 15 July 1770”.",
      de: "Blaue Täfelung, goldene Seide und eine mit Rankenwerk verzierte Decke: ein Himmelbett und ein großes kaiserliches Bildnis, dessen Inschrift vermerkt, es sei „Herrn de Voltaire am 15. Juli 1770 geschenkt“ worden.",
      ru: "Голубые панели, золотистые шёлка и потолок с орнаментом: кровать с балдахином и большой императорский портрет, надпись на котором гласит, что он был «подарен г-ну де Вольтеру 15 июля 1770 года».",
      es: "Boiserie azul, sedas doradas y un techo adornado con roleos: una cama con dosel y un gran retrato imperial cuya inscripción indica que fue «regalado a M. de Voltaire el 15 de julio de 1770».",
      it: "Boiserie azzurre, sete dorate e un soffitto ornato di girali: un letto a baldacchino e un grande ritratto imperiale la cui iscrizione ricorda che fu «donato a M. de Voltaire il 15 luglio 1770».",
      pt: "Lambris azuis, sedas douradas e um teto ornado de volutas: uma cama de dossel e um grande retrato imperial cuja inscrição regista que foi «oferecido a M. de Voltaire a 15 de julho de 1770».",
      nl: "Blauwe lambrisering, goudkleurige zijde en een plafond met rankenornament: een hemelbed en een groot keizerlijk portret waarvan het opschrift vermeldt dat het “op 15 juli 1770 aan M. de Voltaire geschonken” werd.",
      pl: "Niebieska boazeria, złociste jedwabie i sufit zdobiony ornamentem z wici: łoże z baldachimem i duży portret cesarski, którego inskrypcja głosi, że został „podarowany panu de Voltaire 15 lipca 1770 roku”.",
      uk: "Блакитні панелі, золотаві шовки та стеля з орнаментом із завитків: ліжко з балдахіном і великий імператорський портрет, напис на якому свідчить, що його було «подаровано п. де Вольтеру 15 липня 1770 року».",
      zh: "蓝色护墙板、金色丝绸和饰有卷草纹的天花板：一张带华盖的床，以及一幅大型帝王肖像，其题字记载此画于“1770年7月15日赠予德·伏尔泰先生”。",
      ja: "青い羽目板、金色の絹、唐草模様で飾られた天井。天蓋付きの寝台と大きな皇帝の肖像画があり、その銘文には「1770年7月15日、ド・ヴォルテール氏に贈られた」と記されています。",
      ko: "푸른 판벽, 금빛 비단, 덩굴무늬 장식의 천장. 닫집 침대와 커다란 황제 초상화가 있으며, 초상화의 명문에는 “1770년 7월 15일 드 볼테르 씨에게 증정됨”이라고 적혀 있습니다.",
      ar: "ألواح خشبية زرقاء وحرائر ذهبية وسقف مزيّن بزخارف لولبية: سرير بمظلة وصورة إمبراطورية كبيرة يذكر نقشها أنها «أُهديت إلى السيد دو فولتير في 15 يوليو 1770».",
      hi: "नीली काष्ठ-पट्टिकाएँ, सुनहरे रेशम और बेल-बूटेदार अलंकरण वाली छत: एक छत्रयुक्त पलंग और एक बड़ा शाही चित्र, जिसके अभिलेख के अनुसार वह “15 जुलाई 1770 को श्री द वोल्टेयर को भेंट किया गया” था।",
      tr: "Mavi ahşap kaplamalar, altın rengi ipekler ve kıvrım süslemeli bir tavan: sayvanlı bir yatak ve üzerindeki yazıta göre “15 Temmuz 1770’te M. de Voltaire’e hediye edilmiş” büyük bir imparatorluk portresi.",
    },
  },
  "07-chateau-de-voltaire-peintures-mythologiques.jpg": {
    title: {
      fr: "Peintures mythologiques du château",
      en: "Mythological paintings in the château",
      de: "Mythologische Gemälde im Schloss",
      ru: "Мифологические картины в замке",
      es: "Pinturas mitológicas del castillo",
      it: "Dipinti mitologici del castello",
      pt: "Pinturas mitológicas do castelo",
      nl: "Mythologische schilderijen in het kasteel",
      pl: "Obrazy mitologiczne w zamku",
      uk: "Міфологічні картини в замку",
      zh: "城堡中的神话题材画作",
      ja: "城館の神話画",
      ko: "성 안의 신화 그림",
      ar: "لوحات أسطورية في القصر",
      hi: "शातो में पौराणिक चित्र",
      tr: "Şatodaki mitolojik tablolar",
    },
    legend: {
      fr: "Sur les boiseries vert d’eau, deux toiles dans leurs cadres dorés : en haut, la toilette de Vénus, entourée d’amours, avec son char tiré par des cygnes ; en dessous, une scène mythologique éclairée par les candélabres.",
      en: "On the pale green panelling, two canvases in gilded frames: above, the toilette of Venus, surrounded by cupids, with her swan-drawn chariot; below, a mythological scene lit by the candelabra.",
      de: "Auf der blassgrünen Täfelung zwei Gemälde in vergoldeten Rahmen: oben die Toilette der Venus, umgeben von Amoretten, mit ihrem von Schwänen gezogenen Wagen; darunter eine mythologische Szene im Schein der Kerzenleuchter.",
      ru: "На светло-зелёных панелях — два полотна в золочёных рамах: вверху туалет Венеры в окружении амуров, с её колесницей, запряжённой лебедями; внизу — мифологическая сцена в свете канделябров.",
      es: "Sobre la boiserie verde pálido, dos lienzos en marcos dorados: arriba, el tocado de Venus, rodeada de amorcillos, con su carro tirado por cisnes; abajo, una escena mitológica iluminada por los candelabros.",
      it: "Sulle boiserie verde pallido, due tele in cornici dorate: in alto, la toeletta di Venere, circondata da amorini, con il suo carro trainato da cigni; in basso, una scena mitologica illuminata dai candelabri.",
      pt: "Sobre os lambris verde-claros, duas telas em molduras douradas: em cima, a toilette de Vénus, rodeada de cupidos, com o seu carro puxado por cisnes; em baixo, uma cena mitológica iluminada pelos candelabros.",
      nl: "Op de lichtgroene lambrisering twee doeken in vergulde lijsten: boven het toilet van Venus, omringd door amoretten, met haar door zwanen getrokken wagen; onder een mythologisch tafereel in het licht van de kandelaars.",
      pl: "Na bladozielonej boazerii dwa płótna w złoconych ramach: u góry toaleta Wenus w otoczeniu amorków, z jej rydwanem zaprzężonym w łabędzie; poniżej scena mitologiczna oświetlona przez kandelabry.",
      uk: "На блідо-зелених панелях — два полотна в позолочених рамах: угорі туалет Венери в оточенні амурів, з її колісницею, запряженою лебедями; унизу — міфологічна сцена у світлі канделябрів.",
      zh: "浅绿色护墙板上，两幅画作装在鎏金画框中：上方是维纳斯梳妆图，她被众丘比特环绕，旁有天鹅拉的车辇；下方是一幅在烛台映照下的神话场景。",
      ja: "淡い緑の羽目板に、金箔の額に収められた二枚の油彩画。上はキューピッドたちに囲まれ、白鳥の引く車を伴ったヴィーナスの化粧の場面、下は燭台に照らされた神話の一場面です。",
      ko: "연녹색 판벽 위, 금박 액자에 담긴 두 점의 캔버스화. 위쪽은 큐피드들에 둘러싸인 채 백조가 끄는 마차와 함께한 비너스의 단장 장면이고, 아래쪽은 촛대 불빛에 비친 신화의 한 장면입니다.",
      ar: "على الألواح الخشبية الخضراء الفاتحة لوحتان في إطارين مذهّبين: في الأعلى زينة فينوس، تحيط بها الكيوبيدات، مع عربتها التي تجرّها البجعات؛ وفي الأسفل مشهد أسطوري تضيئه الشمعدانات.",
      hi: "हल्की हरी काष्ठ-पट्टिकाओं पर सुनहरे फ़्रेमों में दो कैनवस: ऊपर, कामदेवों से घिरी वीनस का श्रृंगार, हंसों द्वारा खींचे जाने वाले उसके रथ के साथ; नीचे, दीपाधारों की रोशनी में एक पौराणिक दृश्य।",
      tr: "Açık yeşil ahşap kaplamalar üzerinde, yaldızlı çerçeveler içinde iki tuval: üstte, küçük aşk tanrılarıyla çevrili Venüs’ün kuğuların çektiği arabasıyla tuvaleti; altta, şamdanların aydınlattığı mitolojik bir sahne.",
    },
  },
  "08-chateau-de-voltaire-boiseries-tableaux.jpg": {
    title: {
      fr: "Tableaux et boiseries vert d’eau",
      en: "Paintings and pale green panelling",
      de: "Gemälde und blassgrüne Täfelung",
      ru: "Картины и светло-зелёные панели",
      es: "Cuadros y boiserie verde pálido",
      it: "Dipinti e boiserie verde pallido",
      pt: "Quadros e lambris verde-claros",
      nl: "Schilderijen en lichtgroene lambrisering",
      pl: "Obrazy i bladozielona boazeria",
      uk: "Картини та блідо-зелені панелі",
      zh: "画作与浅绿色护墙板",
      ja: "絵画と淡い緑の羽目板",
      ko: "그림과 연녹색 판벽",
      ar: "لوحات وألواح خشبية خضراء فاتحة",
      hi: "चित्र और हल्की हरी काष्ठ-पट्टिकाएँ",
      tr: "Tablolar ve açık yeşil ahşap kaplamalar",
    },
    legend: {
      fr: "Sous un plafond aux rinceaux dorés, des toiles mythologiques dans leurs cadres sculptés, une console dorée aux candélabres et des fauteuils couverts de tapisserie fleurie.",
      en: "Beneath a ceiling of gilded scrolls: mythological canvases in carved frames, a gilded console with candelabra and armchairs covered in floral tapestry.",
      de: "Unter einer Decke mit vergoldetem Rankenwerk: mythologische Gemälde in geschnitzten Rahmen, eine vergoldete Konsole mit Kerzenleuchtern und Sessel mit geblümtem Gobelinbezug.",
      ru: "Под потолком с золочёным орнаментом — мифологические полотна в резных рамах, золочёная консоль с канделябрами и кресла, обитые цветочным гобеленом.",
      es: "Bajo un techo de roleos dorados: lienzos mitológicos en marcos tallados, una consola dorada con candelabros y sillones tapizados con motivos florales.",
      it: "Sotto un soffitto a girali dorati: tele mitologiche in cornici intagliate, una consolle dorata con candelabri e poltrone rivestite di arazzo a fiori.",
      pt: "Sob um teto de volutas douradas: telas mitológicas em molduras entalhadas, uma consola dourada com candelabros e poltronas forradas de tapeçaria florida.",
      nl: "Onder een plafond met vergulde ranken: mythologische doeken in gesneden lijsten, een vergulde console met kandelaars en fauteuils bekleed met gebloemde tapisserie.",
      pl: "Pod sufitem ze złoconym ornamentem z wici: mitologiczne płótna w rzeźbionych ramach, złocona konsola z kandelabrami i fotele obite kwiecistą tapiserią.",
      uk: "Під стелею з позолоченими завитками — міфологічні полотна в різьблених рамах, позолочена консоль із канделябрами та крісла, оббиті квітчастим гобеленом.",
      zh: "鎏金卷草纹天花板下：雕花画框中的神话题材油画、置有烛台的鎏金边桌，以及覆有花卉挂毯面料的扶手椅。",
      ja: "金色の唐草模様の天井の下に、彫刻の施された額の神話画、燭台を載せた金色のコンソール、花柄のタペストリー張りの肘掛け椅子が並びます。",
      ko: "금박 덩굴무늬 천장 아래, 조각 액자에 담긴 신화 그림들, 촛대가 놓인 금박 콘솔, 꽃무늬 태피스트리를 씌운 안락의자들.",
      ar: "تحت سقف مزيّن بزخارف لولبية مذهّبة: لوحات أسطورية في إطارات منحوتة، وطاولة حائط مذهّبة عليها شمعدانات، ومقاعد بذراعين مكسوّة بنسيج مطرّز بالأزهار.",
      hi: "सुनहरे बेल-बूटों वाली छत के नीचे: नक़्क़ाशीदार फ़्रेमों में पौराणिक कैनवस, दीपाधारों से सजी सुनहरी कंसोल-मेज़ और फूलदार टेपेस्ट्री से मढ़ी आरामकुर्सियाँ।",
      tr: "Yaldızlı kıvrım süslemeli bir tavanın altında: oymalı çerçeveler içinde mitolojik tuvaller, şamdanlı yaldızlı bir konsol ve çiçekli goblenle kaplı koltuklar.",
    },
  },
  "09-tableau-allegorique-gloire-de-voltaire.jpg": {
    title: {
      fr: "Tableau allégorique à la gloire de Voltaire",
      en: "Allegorical painting in honour of Voltaire",
      de: "Allegorisches Gemälde zu Ehren Voltaires",
      ru: "Аллегорическая картина во славу Вольтера",
      es: "Cuadro alegórico en honor de Voltaire",
      it: "Dipinto allegorico in onore di Voltaire",
      pt: "Quadro alegórico em honra de Voltaire",
      nl: "Allegorisch schilderij ter ere van Voltaire",
      pl: "Obraz alegoryczny na cześć Woltera",
      uk: "Алегорична картина на честь Вольтера",
      zh: "颂扬伏尔泰的寓意画",
      ja: "ヴォルテールを讃える寓意画",
      ko: "볼테르를 기리는 우의화",
      ar: "لوحة رمزية تكريماً لفولتير",
      hi: "वोल्टेयर के सम्मान में रूपकात्मक चित्र",
      tr: "Voltaire onuruna alegorik tablo",
    },
    legend: {
      fr: "Apollon, couronné de lumière, accueille le philosophe et ses écrits ; la Renommée sonne de la trompette près d’un temple à l’antique, tandis qu’à droite ses adversaires et leurs libelles sont précipités dans les flammes.",
      en: "Apollo, crowned with light, welcomes the philosopher and his writings; Fame sounds her trumpet beside a classical temple, while on the right his adversaries and their pamphlets are cast into the flames.",
      de: "Apollon, von Licht bekrönt, empfängt den Philosophen und seine Schriften; Fama bläst die Posaune neben einem antiken Tempel, während rechts seine Gegner und ihre Pamphlete in die Flammen stürzen.",
      ru: "Аполлон в сиянии принимает философа и его сочинения; Слава трубит у античного храма, а справа его противники и их пасквили низвергаются в пламя.",
      es: "Apolo, coronado de luz, acoge al filósofo y sus escritos; la Fama toca la trompeta junto a un templo clásico, mientras a la derecha sus adversarios y sus libelos son arrojados a las llamas.",
      it: "Apollo, coronato di luce, accoglie il filosofo e i suoi scritti; la Fama suona la tromba accanto a un tempio classico, mentre a destra i suoi avversari e i loro libelli sono gettati tra le fiamme.",
      pt: "Apolo, coroado de luz, acolhe o filósofo e os seus escritos; a Fama toca a trombeta junto a um templo clássico, enquanto à direita os seus adversários e os seus libelos são lançados às chamas.",
      nl: "Apollo, gekroond met licht, verwelkomt de filosoof en zijn geschriften; Fama blaast op haar trompet naast een klassieke tempel, terwijl rechts zijn tegenstanders en hun pamfletten in de vlammen worden geworpen.",
      pl: "Apollo w koronie ze światła przyjmuje filozofa i jego pisma; Sława dmie w trąbę obok antycznej świątyni, a po prawej jego przeciwnicy wraz ze swoimi paszkwilami zostają strąceni w płomienie.",
      uk: "Аполлон, увінчаний світлом, вітає філософа та його твори; Слава сурмить біля античного храму, а праворуч його супротивників та їхні памфлети скидають у полум’я.",
      zh: "头戴光冕的阿波罗迎接这位哲学家及其著作；名望女神在一座古典神庙旁吹响号角，而右侧，他的对手及其讽刺小册子被抛入火焰之中。",
      ja: "光の冠を戴いたアポロンが哲学者とその著作を迎え入れ、古典様式の神殿の傍らでは名声の女神がラッパを吹き鳴らしています。右側では、彼の論敵たちとその誹謗文書が炎の中へと投げ込まれています。",
      ko: "빛의 관을 쓴 아폴론이 철학자와 그의 저작을 맞이하고, 고전 양식의 신전 옆에서는 명성의 여신이 나팔을 붑니다. 오른쪽에서는 그의 적수들과 그들의 비방 문서가 불길 속으로 내던져집니다.",
      ar: "أبولو، المتوَّج بالنور، يستقبل الفيلسوف وكتاباته؛ وربّة الشهرة تنفخ في بوقها بجوار معبد كلاسيكي، بينما يُلقى على اليمين خصومه ومنشوراتهم في اللهب.",
      hi: "प्रकाश से मुकुटित अपोलो दार्शनिक और उनकी रचनाओं का स्वागत करते हैं; कीर्ति की देवी एक शास्त्रीय मंदिर के पास तुरही बजाती है, जबकि दाईं ओर उनके विरोधियों और उनके पर्चों को लपटों में झोंका जा रहा है।",
      tr: "Işıktan bir taç takmış Apollon, filozofu ve yazılarını karşılıyor; Şöhret, klasik bir tapınağın yanında borusunu çalarken, sağda hasımları ve onların hiciv risaleleri alevlere atılıyor.",
    },
  },
  "11-buste-de-voltaire-tableau-jeaurat.jpg": {
    title: {
      fr: "Buste de Voltaire et repas champêtre",
      en: "Bust of Voltaire and a country meal",
      de: "Büste Voltaires und ländliches Mahl",
      ru: "Бюст Вольтера и сельская трапеза",
      es: "Busto de Voltaire y comida campestre",
      it: "Busto di Voltaire e pasto campestre",
      pt: "Busto de Voltaire e refeição campestre",
      nl: "Buste van Voltaire en een landelijke maaltijd",
      pl: "Popiersie Woltera i wiejski posiłek",
      uk: "Погруддя Вольтера та сільська трапеза",
      zh: "伏尔泰半身像与乡间聚餐图",
      ja: "ヴォルテールの胸像と田園の食事",
      ko: "볼테르 흉상과 전원의 식사",
      ar: "تمثال نصفي لفولتير ووليمة ريفية",
      hi: "वोल्टेयर की आवक्ष प्रतिमा और ग्रामीण भोज",
      tr: "Voltaire büstü ve kır yemeği",
    },
    legend: {
      fr: "Devant les boiseries gris-bleu, un buste de Voltaire âgé, en marbre, et un tableau au cadre doré dont le cartel porte le nom de Jeaurat : une joyeuse compagnie attablée sous les arbres, tandis que des pauvres s’approchent.",
      en: "Against grey-blue panelling, a marble bust of the elderly Voltaire and a painting in a gilded frame whose label bears the name Jeaurat: a merry company dining under the trees as poor folk approach.",
      de: "Vor graublauer Täfelung eine Marmorbüste des betagten Voltaire und ein Gemälde im vergoldeten Rahmen, dessen Schild den Namen Jeaurat trägt: eine fröhliche Gesellschaft tafelt unter Bäumen, während sich Arme nähern.",
      ru: "На фоне серо-голубых панелей — мраморный бюст пожилого Вольтера и картина в золочёной раме с табличкой «Jeaurat»: весёлое общество за столом под деревьями, к которому приближаются бедняки.",
      es: "Ante la boiserie gris azulada, un busto de mármol del anciano Voltaire y un cuadro en marco dorado cuya cartela lleva el nombre de Jeaurat: una alegre compañía come bajo los árboles mientras se acercan unos pobres.",
      it: "Contro le boiserie grigio-azzurre, un busto in marmo di Voltaire anziano e un dipinto in cornice dorata il cui cartiglio reca il nome di Jeaurat: un’allegra compagnia a tavola sotto gli alberi, mentre alcuni poveri si avvicinano.",
      pt: "Diante dos lambris cinzento-azulados, um busto de mármore de Voltaire já idoso e um quadro em moldura dourada cuja placa ostenta o nome de Jeaurat: uma alegre companhia à mesa sob as árvores, enquanto alguns pobres se aproximam.",
      nl: "Tegen grijsblauwe lambrisering een marmeren buste van de bejaarde Voltaire en een schilderij in vergulde lijst waarvan het naamplaatje de naam Jeaurat draagt: een vrolijk gezelschap tafelt onder de bomen terwijl armen naderbij komen.",
      pl: "Na tle szaroniebieskiej boazerii marmurowe popiersie sędziwego Woltera i obraz w złoconej ramie z tabliczką z nazwiskiem Jeaurat: wesołe towarzystwo biesiaduje pod drzewami, a tymczasem zbliżają się ubodzy.",
      uk: "На тлі сіро-блакитних панелей — мармурове погруддя літнього Вольтера та картина в позолоченій рамі з табличкою з ім’ям Jeaurat: весела компанія бенкетує під деревами, а до неї наближаються бідняки.",
      zh: "灰蓝色护墙板前，是一尊晚年伏尔泰的大理石半身像，以及一幅鎏金画框的画作，其标牌上写着Jeaurat之名：一群欢乐的人在树下用餐，几位穷人正走近。",
      ja: "灰青色の羽目板を背に、晩年のヴォルテールの大理石の胸像と、銘板にJeauratの名が記された金色の額の絵。木々の下で食卓を囲む陽気な一団に、貧しい人々が近づいてくる場面です。",
      ko: "회청색 판벽을 배경으로 노년의 볼테르를 새긴 대리석 흉상과, 명판에 Jeaurat라는 이름이 적힌 금박 액자 속 그림. 나무 아래에서 즐겁게 식사하는 일행에게 가난한 사람들이 다가오는 장면입니다.",
      ar: "أمام ألواح خشبية رمادية زرقاء، تمثال نصفي من الرخام لفولتير في شيخوخته، ولوحة في إطار مذهّب تحمل بطاقتها اسم Jeaurat: جماعة مرحة تتناول الطعام تحت الأشجار بينما يقترب منها بعض الفقراء.",
      hi: "स्लेटी-नीली काष्ठ-पट्टिकाओं के सामने वृद्ध वोल्टेयर की संगमरमर की आवक्ष प्रतिमा और सुनहरे फ़्रेम में एक चित्र, जिसकी नामपट्टिका पर Jeaurat का नाम है: पेड़ों के नीचे भोजन करती एक प्रसन्न मंडली, जिसकी ओर कुछ ग़रीब लोग बढ़ रहे हैं।",
      tr: "Gri-mavi ahşap kaplamaların önünde, yaşlı Voltaire’in mermer bir büstü ve etiketinde Jeaurat adı yazan yaldız çerçeveli bir tablo: yoksullar yaklaşırken ağaçların altında yemek yiyen neşeli bir topluluk.",
    },
  },
  "12-statue-de-voltaire.jpg": {
    title: {
      fr: "Statue de Voltaire",
      en: "Statue of Voltaire",
      de: "Statue Voltaires",
      ru: "Статуя Вольтера",
      es: "Estatua de Voltaire",
      it: "Statua di Voltaire",
      pt: "Estátua de Voltaire",
      nl: "Standbeeld van Voltaire",
      pl: "Posąg Woltera",
      uk: "Статуя Вольтера",
      zh: "伏尔泰雕像",
      ja: "ヴォルテール像",
      ko: "볼테르 조각상",
      ar: "تمثال فولتير",
      hi: "वोल्टेयर की प्रतिमा",
      tr: "Voltaire heykeli",
    },
    legend: {
      fr: "Dans sa niche de pierre, Voltaire en pied, coiffé de son bonnet, la main sur la hanche, une canne et un livre : le sourire malicieux du « patriarche de Ferney ».",
      en: "In a stone niche, Voltaire stands full-length in his cap, hand on hip, with a cane and a book: the mischievous smile of the “Patriarch of Ferney”.",
      de: "In einer Steinnische steht Voltaire in voller Größe, mit Mütze, die Hand an der Hüfte, mit Stock und Buch: das verschmitzte Lächeln des „Patriarchen von Ferney“.",
      ru: "В каменной нише — Вольтер в полный рост, в своём колпаке, рука на бедре, с тростью и книгой: лукавая улыбка «фернейского патриарха».",
      es: "En una hornacina de piedra, Voltaire de cuerpo entero, con su gorro, la mano en la cadera, un bastón y un libro: la sonrisa pícara del «patriarca de Ferney».",
      it: "In una nicchia di pietra, Voltaire a figura intera, con il suo berretto, la mano sul fianco, un bastone e un libro: il sorriso malizioso del «patriarca di Ferney».",
      pt: "Num nicho de pedra, Voltaire de corpo inteiro, com o seu barrete, a mão na anca, uma bengala e um livro: o sorriso malicioso do «patriarca de Ferney».",
      nl: "In een stenen nis staat Voltaire ten voeten uit, met zijn muts, de hand op de heup, met wandelstok en boek: de schalkse glimlach van de “patriarch van Ferney”.",
      pl: "W kamiennej niszy Wolter w całej postaci, w swojej czapce, z ręką na biodrze, z laską i książką: figlarny uśmiech „patriarchy z Ferney”.",
      uk: "У кам’яній ніші — Вольтер на повний зріст, у своєму ковпаку, з рукою на стегні, з ціпком і книжкою: лукава усмішка «фернейського патріарха».",
      zh: "石砌壁龛中，伏尔泰全身而立，头戴便帽，一手叉腰，拄着手杖、拿着书本：这是“费尔内长老”狡黠的微笑。",
      ja: "石の壁龕に立つ全身像のヴォルテール。帽子をかぶり、片手を腰に当て、杖と本を手にしています。「フェルネーの長老」のいたずらっぽい微笑みです。",
      ko: "돌로 된 벽감 안에 모자를 쓰고 한 손을 허리에 얹은 채 지팡이와 책을 든 볼테르의 전신상이 서 있습니다. “페르네의 족장”의 장난기 어린 미소입니다.",
      ar: "في كوّة حجرية، يقف فولتير بكامل قامته معتمراً قلنسوته، ويده على خصره، ومعه عصا وكتاب: الابتسامة الماكرة لـ«بطريرك فيرني».",
      hi: "पत्थर के आले में वोल्टेयर की पूर्ण-क़द प्रतिमा, टोपी पहने, कमर पर हाथ रखे, छड़ी और पुस्तक लिए: “फ़र्ने के कुलपिता” की शरारती मुस्कान।",
      tr: "Taş bir nişte, başında takkesiyle, eli belinde, bastonu ve kitabıyla ayakta duran Voltaire: “Ferney Patriği”nin muzip gülümsemesi.",
    },
  },
  "13-sylvie-guide-devant-chateau-de-voltaire.jpg": {
    title: {
      fr: "Sylvie, guide officielle, devant le Château de Voltaire",
      en: "Sylvie, official guide, in front of the Château de Voltaire",
      de: "Sylvie, offizielle Gästeführerin, vor dem Schloss Voltaire",
      ru: "Сильви, официальный гид, перед замком Вольтера",
      es: "Sylvie, guía oficial, delante del Château de Voltaire",
      it: "Sylvie, guida ufficiale, davanti al Château de Voltaire",
      pt: "Sylvie, guia oficial, em frente ao Château de Voltaire",
      nl: "Sylvie, officiële gids, voor het Château de Voltaire",
      pl: "Sylvie, oficjalna przewodniczka, przed Château de Voltaire",
      uk: "Сільві, офіційний гід, перед замком Вольтера",
      zh: "官方导游西尔维在伏尔泰城堡前",
      ja: "ヴォルテール城の前に立つ公式ガイドのシルヴィ",
      ko: "볼테르 성 앞의 공식 가이드 실비",
      ar: "سيلفي، المرشدة الرسمية، أمام قصر فولتير",
      hi: "शातो द वोल्टेयर के सामने आधिकारिक गाइड सिल्वी",
      tr: "Resmî rehber Sylvie, Château de Voltaire’in önünde",
    },
    legend: {
      fr: "Sur la pelouse du parc, Sylvie devant la façade rose et blanche du château que Voltaire fit reconstruire à Ferney : le point de départ de vos visites guidées.",
      en: "On the park lawn, Sylvie stands before the pink-and-white façade of the château Voltaire rebuilt at Ferney: the starting point of your guided tours.",
      de: "Auf dem Rasen des Parks steht Sylvie vor der rosa-weißen Fassade des Schlosses, das Voltaire in Ferney neu errichten ließ: der Ausgangspunkt Ihrer Führungen.",
      ru: "На лужайке парка Сильви стоит перед розово-белым фасадом замка, перестроенного Вольтером в Ферне: отсюда начинаются ваши экскурсии.",
      es: "Sobre el césped del parque, Sylvie ante la fachada rosa y blanca del castillo que Voltaire reconstruyó en Ferney: el punto de partida de sus visitas guiadas.",
      it: "Sul prato del parco, Sylvie davanti alla facciata rosa e bianca del castello che Voltaire ricostruì a Ferney: il punto di partenza delle vostre visite guidate.",
      pt: "No relvado do parque, Sylvie diante da fachada cor-de-rosa e branca do castelo que Voltaire reconstruiu em Ferney: o ponto de partida das suas visitas guiadas.",
      nl: "Op het gazon van het park staat Sylvie voor de roze-witte gevel van het kasteel dat Voltaire in Ferney herbouwde: het vertrekpunt van uw rondleidingen.",
      pl: "Na trawniku w parku Sylvie stoi przed różowo-białą fasadą zamku, który Wolter odbudował w Ferney: tu zaczynają się Państwa wycieczki z przewodnikiem.",
      uk: "На галявині парку Сільві стоїть перед рожево-білим фасадом замку, який Вольтер перебудував у Ферне: звідси починаються ваші екскурсії.",
      zh: "在园中草坪上，西尔维站在伏尔泰于费尔内重建的城堡那粉白相间的立面前：这里正是您导览参观的起点。",
      ja: "庭園の芝生の上、ヴォルテールがフェルネーに再建した城館のピンクと白のファサードの前に立つシルヴィ。ここがガイドツアーの出発点です。",
      ko: "공원 잔디밭 위, 볼테르가 페르네에 재건한 성의 분홍빛과 흰빛 파사드 앞에 선 실비. 이곳에서 가이드 투어가 시작됩니다.",
      ar: "على عشب الحديقة، تقف سيلفي أمام الواجهة الوردية والبيضاء للقصر الذي أعاد فولتير بناءه في فيرني: نقطة انطلاق جولاتكم المصحوبة بمرشدة.",
      hi: "पार्क के लॉन पर सिल्वी उस शातो के गुलाबी-सफ़ेद अग्रभाग के सामने खड़ी हैं जिसे वोल्टेयर ने फ़र्ने में फिर से बनवाया था: आपके गाइडेड टूर का प्रारंभ-बिंदु।",
      tr: "Parkın çimenliğinde Sylvie, Voltaire’in Ferney’de yeniden inşa ettirdiği şatonun pembe-beyaz cephesinin önünde duruyor: rehberli turlarınızın başlangıç noktası.",
    },
  },
  "10-chateau-de-voltaire-chambre-alcove.jpg": {
    title: {
      fr: "Une chambre à alcôve du château",
      en: "An alcove bedroom in the château",
      de: "Ein Alkovenzimmer im Schloss",
      ru: "Спальня с альковом в замке",
      es: "Un dormitorio con alcoba del castillo",
      it: "Una camera con alcova del castello",
      pt: "Um quarto com alcova do castelo",
      nl: "Een alkoofkamer in het kasteel",
      pl: "Sypialnia z alkową w zamku",
      uk: "Спальня з альковом у замку",
      zh: "城堡中带凹室的卧室",
      ja: "城館のアルコーヴ付き寝室",
      ko: "성 안의 알코브 침실",
      ar: "غرفة نوم بكوّة في القصر",
      hi: "शातो में आले वाला एक शयनकक्ष",
      tr: "Şatoda alkovlu bir yatak odası",
    },
    legend: {
      fr: "Lit en alcôve tendu de soie jaune à grands motifs, rideaux assortis, faïence peinte et table de toilette : l’intimité d’une chambre du XVIIIe siècle.",
      en: "An alcove bed hung with richly patterned yellow silk, matching curtains, painted faience and a dressing table: the intimacy of an 18th-century bedroom.",
      de: "Ein Alkovenbett mit gelber, reich gemusterter Seide, passende Vorhänge, bemalte Fayence und ein Toilettentisch: die Intimität eines Schlafzimmers des 18. Jahrhunderts.",
      ru: "Кровать в алькове, обтянутая жёлтым узорчатым шёлком, такие же занавеси, расписной фаянс и туалетный столик — уют спальни XVIII века.",
      es: "Una cama en alcoba tapizada de seda amarilla con ricos motivos, cortinas a juego, loza pintada y un tocador: la intimidad de un dormitorio del siglo XVIII.",
      it: "Un letto in alcova rivestito di seta gialla riccamente decorata, tende coordinate, maiolica dipinta e una toeletta: l’intimità di una camera da letto del Settecento.",
      pt: "Uma cama em alcova forrada de seda amarela ricamente estampada, cortinados a condizer, faiança pintada e um toucador: a intimidade de um quarto do século XVIII.",
      nl: "Een alkoofbed bekleed met rijk gedessineerde gele zijde, bijpassende gordijnen, beschilderd faience en een kaptafel: de intimiteit van een 18e-eeuwse slaapkamer.",
      pl: "Łoże w alkowie obite bogato wzorzystym żółtym jedwabiem, dobrane do niego zasłony, malowany fajans i toaletka: intymność XVIII-wiecznej sypialni.",
      uk: "Ліжко в алькові, оббите жовтим шовком із багатим візерунком, такі самі завіси, розписний фаянс і туалетний столик: затишок спальні XVIII століття.",
      zh: "凹室中的床覆以图案华丽的黄色丝绸，配以同色帷幔、彩绘釉陶和梳妆台：一间十八世纪卧室的私密氛围。",
      ja: "豪華な模様の黄色い絹で覆われたアルコーヴの寝台、揃いのカーテン、絵付けされたファイアンス陶器、そして化粧台。18世紀の寝室の親密な雰囲気が漂います。",
      ko: "화려한 무늬의 노란 비단을 두른 알코브 침대, 같은 천의 커튼, 채색 파이앙스 도자기와 화장대. 18세기 침실의 아늑한 분위기가 느껴집니다.",
      ar: "سرير في كوّة مكسوّ بحرير أصفر غنيّ الزخارف، وستائر متناسقة، وخزف مطليّ بالرسوم، وطاولة زينة: حميمية غرفة نوم من القرن الثامن عشر.",
      hi: "समृद्ध बेल-बूटों वाले पीले रेशम से सजा आले में बना पलंग, मेल खाते पर्दे, चित्रित फ़ायंस मृद्भांड और एक श्रृंगार-मेज़: 18वीं सदी के शयनकक्ष की आत्मीयता।",
      tr: "Zengin desenli sarı ipekle kaplı alkovlu bir yatak, takım perdeler, boyalı fayans ve bir tuvalet masası: 18. yüzyıldan bir yatak odasının mahremiyeti.",
    },
  },
};

const dir = join(dirname(fileURLToPath(import.meta.url)), "assets", "gallery");

const fromFileName = (file) => {
  const words = file.replace(/\.[^.]+$/, "").replace(/^\d+[-_ ]*/, "").replace(/[-_]+/g, " ").trim();
  return words.charAt(0).toUpperCase() + words.slice(1);
};

// Pixel size from the file header (JPEG, PNG, WebP), so pages can reserve
// the space before the image loads and structured data can state it.
function imageSize(file) {
  const b = readFileSync(join(dir, file));
  if (b[0] === 0x89 && b.toString("ascii", 1, 4) === "PNG") return { width: b.readUInt32BE(16), height: b.readUInt32BE(20) };
  if (b.toString("ascii", 0, 4) === "RIFF" && b.toString("ascii", 8, 12) === "WEBP") {
    const kind = b.toString("ascii", 12, 16);
    if (kind === "VP8X") return { width: 1 + b.readUIntLE(24, 3), height: 1 + b.readUIntLE(27, 3) };
    if (kind === "VP8 ") return { width: b.readUInt16LE(26) & 0x3fff, height: b.readUInt16LE(28) & 0x3fff };
    if (kind === "VP8L") { const n = b.readUInt32LE(21); return { width: 1 + (n & 0x3fff), height: 1 + ((n >> 14) & 0x3fff) }; }
  }
  if (b[0] === 0xff && b[1] === 0xd8) {
    for (let i = 2; i < b.length - 9; ) {
      if (b[i] !== 0xff) { i++; continue; }
      const marker = b[i + 1];
      if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker)) {
        return { width: b.readUInt16BE(i + 7), height: b.readUInt16BE(i + 5) };
      }
      i += 2 + b.readUInt16BE(i + 2);
    }
  }
  return {};
}

export const photos = readdirSync(dir)
  .filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
  .map((file) => ({
    file,
    ...imageSize(file),
    title: details[file]?.title || { fr: fromFileName(file) },
    legend: details[file]?.legend || {},
  }));
